# Diffusion kernel examples
Anthony Gitter  
November 14, 2023

Compute diffusion kernel using the examples in the slides

In [1]:
# See https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.expm.html
import numpy as np
from scipy.linalg import expm
from math import factorial

In [2]:
# See https://stackoverflow.com/questions/2891790/pretty-print-a-numpy-array-without-scientific-notation-and-with-given-precision
# for print NumPy print formatting
def kernel(beta, laplacian):
    with np.printoptions(precision=2, suppress=True):
        print(expm(-beta * laplacian))

In [3]:
# Create the graph Laplacian for the IsoRank graph
A = np.array([[0,1,0,1,0],
             [1,0,1,0,0],
             [0,1,0,1,1],
             [1,0,1,0,0],
             [0,0,1,0,0]])
D = np.diag(A @ np.ones(5))
L = D - A

In [4]:
L

array([[ 2., -1.,  0., -1.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  3., -1., -1.],
       [-1.,  0., -1.,  2.,  0.],
       [ 0.,  0., -1.,  0.,  1.]])

## Compute the graph diffusion kernel for various $\beta$ values

In [5]:
kernel(0, L)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
kernel(0.5, L)

[[0.47 0.21 0.09 0.21 0.02]
 [0.21 0.46 0.18 0.09 0.05]
 [0.09 0.18 0.34 0.18 0.21]
 [0.21 0.09 0.18 0.46 0.05]
 [0.02 0.05 0.21 0.05 0.67]]


In [7]:
kernel(1, L)

[[0.32 0.24 0.15 0.24 0.06]
 [0.24 0.3  0.19 0.17 0.11]
 [0.15 0.19 0.23 0.19 0.24]
 [0.24 0.17 0.19 0.3  0.11]
 [0.06 0.11 0.24 0.11 0.49]]


In [8]:
kernel(2, L)

[[0.24 0.22 0.19 0.22 0.13]
 [0.22 0.22 0.19 0.2  0.16]
 [0.19 0.19 0.21 0.19 0.22]
 [0.22 0.2  0.19 0.22 0.16]
 [0.13 0.16 0.22 0.16 0.33]]


In [9]:
kernel(10, L)

[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]


## Compute powers of the Laplacian
Show the first terms of the matrix exponential series

In [10]:
# First only the numerator, ignoring beta
product = L
for i in range(1,6):
    print(f'L^{i}')
    print(product)
    product = product @ L
    print()

L^1
[[ 2. -1.  0. -1.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  3. -1. -1.]
 [-1.  0. -1.  2.  0.]
 [ 0.  0. -1.  0.  1.]]

L^2
[[ 6. -4.  2. -4.  0.]
 [-4.  6. -5.  2.  1.]
 [ 2. -5. 12. -5. -4.]
 [-4.  2. -5.  6.  1.]
 [ 0.  1. -4.  1.  2.]]

L^3
[[ 20. -16.  14. -16.  -2.]
 [-16.  21. -24.  13.   6.]
 [ 14. -24.  50. -24. -16.]
 [-16.  13. -24.  21.   6.]
 [ -2.   6. -16.   6.   6.]]

L^4
[[  72.  -66.   76.  -66.  -16.]
 [ -66.   82. -112.   66.   30.]
 [  76. -112.  214. -112.  -66.]
 [ -66.   66. -112.   82.   30.]
 [ -16.   30.  -66.   30.   22.]]

L^5
[[ 276. -280.  376. -280.  -92.]
 [-280.  342. -514.  310.  142.]
 [ 376. -514.  932. -514. -280.]
 [-280.  310. -514.  342.  142.]
 [ -92.  142. -280.  142.   88.]]



In [11]:
# Now show it with the denominator
product = L
with np.printoptions(precision=2, suppress=True):
    for i in range(1,6):
        print(f'L^{i}/{i}!')
        print(product / factorial(i))
        product = product @ L
        print()

L^1/1!
[[ 2. -1.  0. -1.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  3. -1. -1.]
 [-1.  0. -1.  2.  0.]
 [ 0.  0. -1.  0.  1.]]

L^2/2!
[[ 3.  -2.   1.  -2.   0. ]
 [-2.   3.  -2.5  1.   0.5]
 [ 1.  -2.5  6.  -2.5 -2. ]
 [-2.   1.  -2.5  3.   0.5]
 [ 0.   0.5 -2.   0.5  1. ]]

L^3/3!
[[ 3.33 -2.67  2.33 -2.67 -0.33]
 [-2.67  3.5  -4.    2.17  1.  ]
 [ 2.33 -4.    8.33 -4.   -2.67]
 [-2.67  2.17 -4.    3.5   1.  ]
 [-0.33  1.   -2.67  1.    1.  ]]

L^4/4!
[[ 3.   -2.75  3.17 -2.75 -0.67]
 [-2.75  3.42 -4.67  2.75  1.25]
 [ 3.17 -4.67  8.92 -4.67 -2.75]
 [-2.75  2.75 -4.67  3.42  1.25]
 [-0.67  1.25 -2.75  1.25  0.92]]

L^5/5!
[[ 2.3  -2.33  3.13 -2.33 -0.77]
 [-2.33  2.85 -4.28  2.58  1.18]
 [ 3.13 -4.28  7.77 -4.28 -2.33]
 [-2.33  2.58 -4.28  2.85  1.18]
 [-0.77  1.18 -2.33  1.18  0.73]]



## Example calculations for HotNet heat kernel

In [12]:
gamma = 0.5
L_gamma = L + gamma * np.eye(5)

In [13]:
L_gamma

array([[ 2.5, -1. ,  0. , -1. ,  0. ],
       [-1. ,  2.5, -1. ,  0. ,  0. ],
       [ 0. , -1. ,  3.5, -1. , -1. ],
       [-1. ,  0. , -1. ,  2.5,  0. ],
       [ 0. ,  0. , -1. ,  0. ,  1.5]])

In [14]:
b = np.array([1,0,0,0,0]) # source node
f = np.array([0.8,0.7,0.6,0.55,0.2]) # invention diffusion at t

In [15]:
# diffusion rate
-L_gamma @ f + b

array([ 0.25 , -0.35 , -0.65 ,  0.025,  0.3  ])