# Graph diffusion examples
Anthony Gitter  
November 8, 2022

Run random walk with restarts using the examples in the slides and some extreme examples

In [1]:
import numpy as np

In [2]:
# Column-normalized adjacency matrix
W = np.array([[0,0.5,0,0.5,0],
             [0.5,0,1/3,0,0],
             [0,0.5,0,0.5,1],
             [0.5,0,1/3,0,0],
             [0,0,1/3,0,0]])

In [3]:
# set seeds
p0 = np.array([0.5,0.5,0,0,0])

In [4]:
# Function uses some global variables
def rwr(r, iterations):
    print(f'r: {r}')
    pt = p0
    for i in range(iterations+1):
        print(f'Iteration {i}')
        print(pt)
        pt = (1-r)*W@pt+r*p0

In [5]:
rwr(0.7,6)

r: 0.7
Iteration 0
[0.5 0.5 0.  0.  0. ]
Iteration 1
[0.425 0.425 0.075 0.075 0.   ]
Iteration 2
[0.425   0.42125 0.075   0.07125 0.0075 ]
Iteration 3
[0.423875 0.42125  0.076125 0.07125  0.0075  ]
Iteration 4
[0.423875   0.42119375 0.076125   0.07119375 0.0076125 ]
Iteration 5
[0.42385812 0.42119375 0.07614188 0.07119375 0.0076125 ]
Iteration 6
[0.42385812 0.42119291 0.07614188 0.07119291 0.00761419]


In [6]:
rwr(0.5,8)

r: 0.5
Iteration 0
[0.5 0.5 0.  0.  0. ]
Iteration 1
[0.375 0.375 0.125 0.125 0.   ]
Iteration 2
[0.375      0.36458333 0.125      0.11458333 0.02083333]
Iteration 3
[0.36979167 0.36458333 0.13020833 0.11458333 0.02083333]
Iteration 4
[0.36979167 0.36414931 0.13020833 0.11414931 0.02170139]
Iteration 5
[0.36957465 0.36414931 0.13042535 0.11414931 0.02170139]
Iteration 6
[0.36957465 0.36413122 0.13042535 0.11413122 0.02173756]
Iteration 7
[0.36956561 0.36413122 0.13043439 0.11413122 0.02173756]
Iteration 8
[0.36956561 0.36413047 0.13043439 0.11413047 0.02173906]


In [7]:
rwr(0,20)

r: 0
Iteration 0
[0.5 0.5 0.  0.  0. ]
Iteration 1
[0.25 0.25 0.25 0.25 0.  ]
Iteration 2
[0.25       0.20833333 0.25       0.20833333 0.08333333]
Iteration 3
[0.20833333 0.20833333 0.29166667 0.20833333 0.08333333]
Iteration 4
[0.20833333 0.20138889 0.29166667 0.20138889 0.09722222]
Iteration 5
[0.20138889 0.20138889 0.29861111 0.20138889 0.09722222]
Iteration 6
[0.20138889 0.20023148 0.29861111 0.20023148 0.09953704]
Iteration 7
[0.20023148 0.20023148 0.29976852 0.20023148 0.09953704]
Iteration 8
[0.20023148 0.20003858 0.29976852 0.20003858 0.09992284]
Iteration 9
[0.20003858 0.20003858 0.29996142 0.20003858 0.09992284]
Iteration 10
[0.20003858 0.20000643 0.29996142 0.20000643 0.09998714]
Iteration 11
[0.20000643 0.20000643 0.29999357 0.20000643 0.09998714]
Iteration 12
[0.20000643 0.20000107 0.29999357 0.20000107 0.09999786]
Iteration 13
[0.20000107 0.20000107 0.29999893 0.20000107 0.09999786]
Iteration 14
[0.20000107 0.20000018 0.29999893 0.20000018 0.09999964]
Iteration 15
[0.2000

In [8]:
rwr(1,1)

r: 1
Iteration 0
[0.5 0.5 0.  0.  0. ]
Iteration 1
[0.5 0.5 0.  0.  0. ]
